URL_SERVICE = "https://cnt-6f3bbc1e-2d25-4582-8383-49ac990fde11.containerhub.tripleten-services.com"
CREATE_USER_PATH = "/api/v1/users/"
KITS_PATH = "/api/v1/kits"
DOC_PATH = "/docs/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"